# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/src/backend/worker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/src/infrastructure"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "weekly"